# =========================================================
# ml_signal_engine.py
# ML-Based Trading Signal Generation
# Leverages features from feature_engine.py with XGBoost
# Walk-forward validation to prevent future data leakage
# =========================================================

import numpy as np
import pandas as pd
import xgboost as xgb
import duckdb
from pathlib import Path
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, 
    roc_auc_score, confusion_matrix, classification_report
)
import pickle
import time
import sys

from logger_config import (
    log_info, log_error, log_exception, log_warning,
    log_section, log_pipeline_start, log_pipeline_end, log_metrics
)

# Configuration
FEATURES_PATH = Path(__file__).parent.parent / "database" / "stock_features.parquet"
MODELS_PATH = Path(__file__).parent.parent / "database" / "ml_models"
SIGNALS_PATH = Path(__file__).parent.parent / "database" / "ml_signals.parquet"
PERFORMANCE_PATH = Path(__file__).parent.parent / "database" / "model_performance.parquet"

# Model hyperparameters
XGB_PARAMS = {
    'max_depth': 7,           # Increased from 5 (more model capacity)
    'n_estimators': 200,      # Increased from 100 (more trees)
    'learning_rate': 0.05,    # Reduced from 0.1 (slower, more careful learning)
    'subsample': 0.7,         # Reduced from 0.8 (more regularization)
    'colsample_bytree': 0.7,  # Reduced from 0.8 (feature subsampling)
    'gamma': 1.0,             # Minimum loss reduction for split
    'reg_alpha': 0.5,         # L1 regularization
    'reg_lambda': 1.0,        # L2 regularization
    'random_state': 42,
    'verbosity': 0
}

# Signal generation thresholds
BULLISH_THRESHOLD = 0.60  # Confidence threshold for buy signal
BEARISH_THRESHOLD = 0.40  # Confidence threshold for sell signal
TARGET_FORWARD_DAYS = 10   # Predict price movement N days ahead (10 days more predictable than 5)

# Feature selection
META_COLS = ['ticker', 'report_date', 'close', 'volume', 'sector', 'GICS Sub-Industry', 'stock_name']
DROP_COLS = ['open', 'high', 'low', 'adj_close']  # Raw OHLCV columns

# =========================================================
# HELPER FUNCTIONS
# =========================================================

def load_features_from_parquet():
    """
    Load computed features from parquet file generated by feature_engine.
    Returns DataFrame with features ready for ML training.
    """
    if not FEATURES_PATH.exists():
        raise FileNotFoundError(
            f"Feature parquet not found: {FEATURES_PATH}\n"
            f"Run feature_engine.py first to generate features."
        )
    
    log_info(f"Loading features from {FEATURES_PATH.name}...")
    load_start = time.perf_counter()
    
    # Load via DuckDB for efficiency
    conn = duckdb.connect()
    df = conn.execute(f"SELECT * FROM read_parquet('{FEATURES_PATH}')").df()
    conn.close()
    
    load_time = time.perf_counter() - load_start
    log_info(f"Loaded {len(df):,} rows, {len(df.columns)} columns in {load_time:.1f}s")
    
    return df

def validate_features(df):
    """Validate feature DataFrame for ML pipeline."""
    # Check required columns
    required = ['ticker', 'report_date', 'close', 'volume']
    missing = [col for col in required if col not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")
    
    # Check data types
    if df['close'].dtype in ['object', 'string']:
        df['close'] = pd.to_numeric(df['close'], errors='coerce')
    
    # Drop rows with NaN close/volume
    initial_rows = len(df)
    df = df.dropna(subset=['close', 'volume'])
    dropped = initial_rows - len(df)
    if dropped > 0:
        log_warning(f"Dropped {dropped} rows with missing close/volume")
    
    return df

def create_target_variable(df, forward_days=TARGET_FORWARD_DAYS):
    """
    Create binary classification target: 1 if price rises in next N days, else 0.
    Prevents look-ahead bias by only creating targets where future data exists.
    Uses shift() for robust forward-looking window.
    """
    # Ensure data is sorted by ticker and date
    df = df.sort_values(['ticker', 'report_date']).reset_index(drop=True)
    
    # Create future price column (shifted by forward_days for each ticker)
    df['future_close'] = df.groupby('ticker')['close'].shift(-forward_days)
    
    # Create target: 1 if price rises, 0 otherwise
    df['target'] = (df['future_close'] > df['close']).astype(int)
    
    # Drop rows where we don't have future data
    initial = len(df)
    df = df.dropna(subset=['future_close']).reset_index(drop=True)
    dropped = initial - len(df)
    log_info(f"Created targets: {dropped:,} rows removed (not enough future data)")
    
    # Drop the temporary future_close column
    df = df.drop('future_close', axis=1)
    
    return df

def get_feature_columns(df):
    """Extract feature column names (exclude metadata and raw OHLCV)."""
    features = [col for col in df.columns 
                if col not in META_COLS + DROP_COLS + ['target']]
    return features

def prepare_training_data(df, feature_cols):
    """Prepare X, y, and handle NaN values in features."""
    # Drop NaN values
    initial = len(df)
    df = df.dropna(subset=feature_cols + ['target']).reset_index(drop=True)
    dropped = initial - len(df)
    if dropped > 0:
        log_warning(f"Dropped {dropped:,} rows with NaN features ({dropped/initial*100:.1f}%)")
    
    X = df[feature_cols].values
    y = df['target'].values
    
    return X, y, df

def load_sectors_from_csv():
    """
    Load ticker-to-sector mapping from tickers.csv.
    Expected format: ticker,sector
    If sector column missing, fetches from yfinance (slower but works).
    """
    tickers_path = Path(__file__).parent.parent / "tickers.csv"
    
    try:
        df = pd.read_csv(tickers_path)
        
        if "sector" in df.columns:
            log_info(f"Loaded {len(df)} tickers with sector information")
            return dict(zip(df['ticker'], df['sector']))
        elif "Sector" in df.columns:
            log_info(f"Loaded {len(df)} tickers with sector information")
            return dict(zip(df['ticker'], df['Sector']))
        else:
            log_warning("No sector column in tickers.csv, will fetch from yfinance...")
            return None
    except Exception as e:
        log_error(f"Could not load sectors: {e}")
        return None

def get_sector_for_ticker(ticker):
    """Fetch sector for a single ticker from yfinance."""
    try:
        info = yf.Ticker(ticker).info
        return info.get('sector', 'Unknown')
    except:
        return 'Unknown'

def train_and_predict_sector(sector_df, feature_cols, sector_name):
    """
    Train XGBoost model with walk-forward validation for entire sector.
    One model for all stocks in the sector.
    Calculates performance metrics: accuracy, precision, recall, F1, ROC-AUC.
    Returns tuple: (signals_df, performance_metrics_dict)
    """
    try:
        X, y, df = prepare_training_data(sector_df, feature_cols)
        
        if len(X) < 100:
            log_warning(f"  {sector_name}: Insufficient samples ({len(X)} < 100), skipping")
            return None, None
        
        # Diagnostic: Check feature-target correlation (only for first sector to avoid spam)
        if sector_name == sorted(sector_df['sector'].unique())[0]:
            feature_target_corr = np.abs([np.corrcoef(X[:, i], y)[0, 1] for i in range(min(10, X.shape[1]))])
            max_corr = np.max(feature_target_corr)
            log_info(f"  Max feature-target correlation: {max_corr:.4f} (>0.1 needed for predictive power)")
            if max_corr < 0.05:
                log_warning(
                    "  ⚠️  Very weak feature-target correlation (<0.05).\n"
                    "     Technical indicators are not predictive of 10-day returns.\n"
                    "     Consider using rule-based signal_engine.py instead of ML."
                )
        
        # Walk-forward validation (time series split)
        n_splits = min(3, len(X) // 100)  # Reduced from 5 to 3 for speed
        tscv = TimeSeriesSplit(n_splits=n_splits)
        
        all_signals = []
        all_proba = []
        all_actuals = []
        indices = []
        
        # Metrics aggregation across all splits
        all_accuracies = []
        all_precisions = []
        all_recalls = []
        all_f1s = []
        all_roc_aucs = []
        
        for fold, (train_idx, test_idx) in enumerate(tscv.split(X), 1):
            X_train, X_test = X[train_idx], X[test_idx]
            y_train, y_test = y[train_idx], y[test_idx]
            
            # Scale features
            scaler = StandardScaler()
            X_train_scaled = scaler.fit_transform(X_train)
            X_test_scaled = scaler.transform(X_test)
            
            # Train model with class weight balancing for imbalanced targets
            n_neg = np.sum(y_train == 0)
            n_pos = np.sum(y_train == 1)
            scale_pos_weight = max(n_neg / (n_pos + 1), 0.5)  # Avoid extreme imbalance
            
            params = XGB_PARAMS.copy()
            params['scale_pos_weight'] = scale_pos_weight
            
            model = xgb.XGBClassifier(**params)
            model.fit(X_train_scaled, y_train, verbose=False)
            
            # Generate predictions
            proba = model.predict_proba(X_test_scaled)  # [prob_bearish, prob_bullish]
            prob_bullish = proba[:, 1]
            preds = model.predict(X_test_scaled)
            
            # Generate signals: 1 (buy), 0 (hold), -1 (sell)
            signals = np.where(
                prob_bullish > BULLISH_THRESHOLD, 
                1, 
                np.where(prob_bullish < BEARISH_THRESHOLD, -1, 0)
            )
            
            # Calculate metrics
            accuracy = accuracy_score(y_test, preds)
            precision = precision_score(y_test, preds, zero_division=0)
            recall = recall_score(y_test, preds, zero_division=0)
            f1 = f1_score(y_test, preds, zero_division=0)
            roc_auc = roc_auc_score(y_test, prob_bullish)
            
            all_accuracies.append(accuracy)
            all_precisions.append(precision)
            all_recalls.append(recall)
            all_f1s.append(f1)
            all_roc_aucs.append(roc_auc)
            
            all_signals.extend(signals)
            all_proba.extend(prob_bullish)
            all_actuals.extend(y_test)
            indices.extend(test_idx)
        
        # Rebuild result dataframe with signals
        result = df.iloc[indices].copy()
        result['ml_signal'] = all_signals
        result['ml_probability'] = all_proba
        result = result[['ticker', 'report_date', 'close', 'ml_signal', 'ml_probability', 'target']]
        
        # Aggregate performance metrics
        performance = {
            'sector': sector_name,
            'total_samples': len(X),
            'n_folds': len(all_accuracies),
            'accuracy': np.mean(all_accuracies),
            'accuracy_std': np.std(all_accuracies),
            'precision': np.mean(all_precisions),
            'precision_std': np.std(all_precisions),
            'recall': np.mean(all_recalls),
            'recall_std': np.std(all_recalls),
            'f1_score': np.mean(all_f1s),
            'f1_score_std': np.std(all_f1s),
            'roc_auc': np.mean(all_roc_aucs),
            'roc_auc_std': np.std(all_roc_aucs),
            'bullish_signals': int(np.sum(np.array(all_signals) == 1)),
            'bearish_signals': int(np.sum(np.array(all_signals) == -1)),
            'hold_signals': int(np.sum(np.array(all_signals) == 0)),
        }
        
        return result, performance
    
    except Exception as e:
        log_error(f"  {sector_name}: {str(e)}")
        return None, None

def generate_ml_signals(validate_features_flag=True):
    """
    Generate ML-based buy/sell signals using SECTOR-BASED CLUSTERING.
    
    Process:
    1. Load features from parquet (created by feature_engine)
    2. Load sector information from tickers.csv
    3. Create binary classification targets (10-day forward return)
    4. Train ONE XGBoost model PER SECTOR (not per ticker)
    5. Generate signals based on predicted probabilities
    6. Save results to parquet
    
    Runtime: ~10-15 minutes (vs 1-2 hours with per-ticker models)
    
    Returns:
        DataFrame with columns: [ticker, report_date, close, ml_signal, ml_probability, target]
    """
    log_section("ML Signal Generation (Sector-Based)")
    
    # -------------------------
    # LOAD & VALIDATE FEATURES
    # -------------------------
    try:
        df_feat = load_features_from_parquet()
    except FileNotFoundError as e:
        log_error(str(e))
        return None
    
    if validate_features_flag:
        df_feat = validate_features(df_feat)
    
    n_tickers = df_feat['ticker'].nunique()
    log_info(f"Processing {n_tickers} tickers with {len(df_feat):,} rows")
    
    # -------------------------
    # LOAD SECTOR INFORMATION
    # -------------------------
    ticker_sectors = load_sectors_from_csv()
    
    if ticker_sectors is None:
        log_warning("Sector CSV not available, fetching from yfinance (slow)...")
        ticker_sectors = {}
        for ticker in df_feat['ticker'].unique():
            ticker_sectors[ticker] = get_sector_for_ticker(ticker)
            time.sleep(0.2)  # Rate limit
    
    # Add sector column
    df_feat['sector'] = df_feat['ticker'].map(ticker_sectors).fillna('Unknown')
    
    n_sectors = df_feat['sector'].nunique()
    sector_dist = df_feat['ticker'].groupby(df_feat['sector']).nunique()
    log_info(f"Grouped into {n_sectors} sectors")
    for sector, count in sector_dist.items():
        log_info(f"  {sector}: {count} tickers")
    
    # -------------------------
    # CREATE TARGETS (10-day forward prediction)
    # -------------------------
    log_info("Creating target variables (10-day forward returns)...")
    df_feat = create_target_variable(df_feat, TARGET_FORWARD_DAYS)
    
    # -------------------------
    # GET FEATURE COLUMNS & VALIDATE TARGET DISTRIBUTION
    # -------------------------
    feature_cols = get_feature_columns(df_feat)
    log_info(f"Using {len(feature_cols)} features for training")
    
    # Check target class balance
    target_dist = df_feat['target'].value_counts(normalize=True)
    log_info(f"Target distribution: Bearish (0): {target_dist.get(0, 0):.1%}, Bullish (1): {target_dist.get(1, 0):.1%}")
    
    # Warning if target is nearly 50/50 (suggests random/unpredictable)
    if 0.48 <= target_dist.get(1, 0.5) <= 0.52:
        log_warning(
            "⚠️  Target distribution is ~50/50, suggesting 10-day forward returns are random/unpredictable.\n"
            "    Technical indicators may not have predictive power for short-term price movements.\n"
            "    Consider: (1) Longer horizons (20-30 days), (2) Relative returns vs SPY, or (3) Fundamental features."
        )
    
    # -------------------------
    # TRAIN & GENERATE SIGNALS (PER SECTOR, NOT PER TICKER)
    # -------------------------
    log_info(f"Training sector models and generating signals...")
    
    all_signals = []
    all_performance = []
    successful_sectors = []
    failed_sectors = []
    
    process_start = time.perf_counter()
    
    for i, sector in enumerate(sorted(df_feat['sector'].unique()), 1):
        sector_df = df_feat[df_feat['sector'] == sector].sort_values('report_date').reset_index(drop=True)
        sector_tickers = sector_df['ticker'].nunique()
        
        log_info(f"  [{i}/{n_sectors}] {sector} ({len(sector_df)} rows, {sector_tickers} tickers)")
        
        result, perf = train_and_predict_sector(sector_df, feature_cols, sector)
        if result is not None:
            all_signals.append(result)
            all_performance.append(perf)
            successful_sectors.append(sector)
            # Log sector-specific metrics
            log_info(f"      Accuracy: {perf['accuracy']:.3f} | F1: {perf['f1_score']:.3f} | ROC-AUC: {perf['roc_auc']:.3f}")
        else:
            failed_sectors.append(sector)
    
    process_time = time.perf_counter() - process_start
    log_info(f"Sector model training: {process_time:.1f}s ({n_sectors/max(process_time, 0.1):.1f} sectors/sec)")
    
    if not all_signals:
        log_error("No signals generated")
        return None
    
    # -------------------------
    # COMBINE RESULTS
    # -------------------------
    df_signals = pd.concat(all_signals, ignore_index=True).sort_values(['ticker', 'report_date'])
    
    log_info(f"Generated signals for {len(successful_sectors)} sectors")
    if failed_sectors:
        log_warning(f"Failed: {', '.join(failed_sectors)}")
    
    # -------------------------
    # SAVE SIGNALS TO PARQUET
    # -------------------------
    MODELS_PATH.mkdir(exist_ok=True)
    log_info(f"Saving signals to {SIGNALS_PATH.name}...")
    
    save_start = time.perf_counter()
    conn = duckdb.connect()
    conn.execute(f"COPY df_signals TO '{SIGNALS_PATH}' (FORMAT PARQUET, COMPRESSION 'snappy')")
    conn.close()
    save_time = time.perf_counter() - save_start
    
    file_size_mb = SIGNALS_PATH.stat().st_size / (1024 * 1024)
    log_info(f"Signals saved: {len(df_signals):,} rows, {file_size_mb:.1f} MB in {save_time:.1f}s")
    
    # -------------------------
    # SAVE MODEL PERFORMANCE METRICS TO PARQUET
    # -------------------------
    if all_performance:
        log_info(f"Saving sector model performance metrics to {PERFORMANCE_PATH.name}...")
        df_perf = pd.DataFrame(all_performance)
        
        perf_start = time.perf_counter()
        conn = duckdb.connect()
        conn.execute(f"COPY df_perf TO '{PERFORMANCE_PATH}' (FORMAT PARQUET, COMPRESSION 'snappy')")
        conn.close()
        perf_time = time.perf_counter() - perf_start
        
        log_info(f"Performance metrics saved in {perf_time:.1f}s")
        
        # Log aggregated performance stats
        log_info("Aggregated Sector Model Performance:")
        log_info(f"  Accuracy:  {df_perf['accuracy'].mean():.3f} ± {df_perf['accuracy'].std():.3f}")
        log_info(f"  Precision: {df_perf['precision'].mean():.3f} ± {df_perf['precision'].std():.3f}")
        log_info(f"  Recall:    {df_perf['recall'].mean():.3f} ± {df_perf['recall'].std():.3f}")
        log_info(f"  F1-Score:  {df_perf['f1_score'].mean():.3f} ± {df_perf['f1_score'].std():.3f}")
        log_info(f"  ROC-AUC:   {df_perf['roc_auc'].mean():.3f} ± {df_perf['roc_auc'].std():.3f}")
    
    # -------------------------
    # SIGNAL STATISTICS
    # -------------------------
    signal_dist = df_signals['ml_signal'].value_counts()
    log_metrics({
        "Total Signals": len(df_signals),
        "Buy (1)": signal_dist.get(1, 0),
        "Hold (0)": signal_dist.get(0, 0),
        "Sell (-1)": signal_dist.get(-1, 0),
        "Avg Probability": f"{df_signals['ml_probability'].mean():.3f}",
        "Sectors": len(successful_sectors),
        "Tickers": df_signals['ticker'].nunique()
    })
    
    return df_signals

# =========================================================
# QUERY & ANALYSIS UTILITIES
# =========================================================

def get_latest_signals(n_signals=20):
    """Retrieve latest N signals for all tickers."""
    if not SIGNALS_PATH.exists():
        log_error(f"Signals file not found: {SIGNALS_PATH}")
        return None
    
    conn = duckdb.connect()
    query = f"""
        SELECT * FROM read_parquet('{SIGNALS_PATH}')
        ORDER BY report_date DESC, ticker
        LIMIT {n_signals}
    """
    result = conn.execute(query).df()
    conn.close()
    return result

def get_signals_by_ticker(ticker, limit=50):
    """Get all signals for a specific ticker."""
    if not SIGNALS_PATH.exists():
        log_error(f"Signals file not found: {SIGNALS_PATH}")
        return None
    
    conn = duckdb.connect()
    query = f"""
        SELECT * FROM read_parquet('{SIGNALS_PATH}')
        WHERE ticker = '{ticker}'
        ORDER BY report_date DESC
        LIMIT {limit}
    """
    result = conn.execute(query).df()
    conn.close()
    return result

def get_signal_statistics():
    """Get aggregated signal statistics."""
    if not SIGNALS_PATH.exists():
        log_error(f"Signals file not found: {SIGNALS_PATH}")
        return None
    
    conn = duckdb.connect()
    query = f"""
        SELECT 
            ticker,
            COUNT(*) as total_signals,
            SUM(CASE WHEN ml_signal = 1 THEN 1 ELSE 0 END) as buy_signals,
            SUM(CASE WHEN ml_signal = -1 THEN 1 ELSE 0 END) as sell_signals,
            SUM(CASE WHEN ml_signal = 0 THEN 1 ELSE 0 END) as hold_signals,
            AVG(ml_probability) as avg_probability,
            MAX(report_date) as latest_date
        FROM read_parquet('{SIGNALS_PATH}')
        GROUP BY ticker
        ORDER BY ticker
    """
    result = conn.execute(query).df()
    conn.close()
    return result

def get_model_performance():
    """Get model performance metrics for all tickers."""
    if not PERFORMANCE_PATH.exists():
        log_error(f"Performance metrics file not found: {PERFORMANCE_PATH}")
        return None
    
    conn = duckdb.connect()
    df = conn.execute(f"SELECT * FROM read_parquet('{PERFORMANCE_PATH}') ORDER BY ticker").df()
    conn.close()
    return df

def get_model_performance_by_sector(sector):
    """Get performance metrics for specific sector."""
    if not PERFORMANCE_PATH.exists():
        log_error(f"Performance metrics file not found: {PERFORMANCE_PATH}")
        return None
    
    conn = duckdb.connect()
    query = f"""
        SELECT * FROM read_parquet('{PERFORMANCE_PATH}')
        WHERE sector = '{sector}'
    """
    result = conn.execute(query).df()
    conn.close()
    
    if len(result) == 0:
        log_warning(f"No performance metrics found for sector {sector}")
        return None
    
    return result.iloc[0]

def get_model_performance_by_ticker(ticker):
    """Get performance metrics for specific ticker (looks up sector)."""
    if not PERFORMANCE_PATH.exists():
        log_error(f"Performance metrics file not found: {PERFORMANCE_PATH}")
        return None
    
    # First, load ticker-sector mapping
    ticker_sectors = load_sectors_from_csv()
    if ticker_sectors is None or ticker not in ticker_sectors:
        log_warning(f"Sector information not found for {ticker}")
        return None
    
    sector = ticker_sectors[ticker]
    return get_model_performance_by_sector(sector)

def display_model_performance_summary():
    """Display formatted model performance summary."""
    df = get_model_performance()
    if df is None or len(df) == 0:
        print("No performance metrics available")
        return
    
    print("\n" + "="*100)
    print("MODEL PERFORMANCE SUMMARY (All Sectors)")
    print("="*100)
    
    # Summary statistics
    print("\nAGGREGATED METRICS:")
    print(f"  Total Sectors:    {len(df)}")
    print(f"  Accuracy:         {df['accuracy'].mean():.4f} ± {df['accuracy'].std():.4f}")
    print(f"  Precision:        {df['precision'].mean():.4f} ± {df['precision'].std():.4f}")
    print(f"  Recall:           {df['recall'].mean():.4f} ± {df['recall'].std():.4f}")
    print(f"  F1-Score:         {df['f1_score'].mean():.4f} ± {df['f1_score'].std():.4f}")
    print(f"  ROC-AUC:          {df['roc_auc'].mean():.4f} ± {df['roc_auc'].std():.4f}")
    
    # Top performers
    print("\nTOP PERFORMERS (by ROC-AUC):")
    top_df = df.nlargest(10, 'roc_auc')[['sector', 'accuracy', 'precision', 'recall', 'f1_score', 'roc_auc', 'total_samples']]
    print(top_df.to_string(index=False))
    
    # Bottom performers
    print("\nBOTTOM PERFORMERS (by ROC-AUC):")
    bottom_df = df.nsmallest(10, 'roc_auc')[['sector', 'accuracy', 'precision', 'recall', 'f1_score', 'roc_auc', 'total_samples']]
    print(bottom_df.to_string(index=False))
    
    # Full detailed table
    print("\nDETAILED PERFORMANCE (All Sectors):")
    detailed = df[[
        'sector', 'total_samples', 'n_folds', 'accuracy', 'precision', 
        'recall', 'f1_score', 'roc_auc', 'bullish_signals', 'bearish_signals'
    ]].copy()
    detailed['accuracy'] = detailed['accuracy'].round(4)
    detailed['precision'] = detailed['precision'].round(4)
    detailed['recall'] = detailed['recall'].round(4)
    detailed['f1_score'] = detailed['f1_score'].round(4)
    detailed['roc_auc'] = detailed['roc_auc'].round(4)
    print(detailed.to_string(index=False))
    
    print("="*100 + "\n")

# =========================================================
# RUN
# =========================================================

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="ML-based trading signal generation")
    parser.add_argument("--query", type=str, choices=['latest', 'stats', 'ticker', 'accuracy', 'performance'],
                       help="Query mode: latest signals, statistics, ticker signals, model accuracy, or full performance")
    parser.add_argument("--ticker", type=str, help="Ticker symbol for query mode")
    parser.add_argument("--limit", type=int, default=20, help="Limit results (default: 20)")
    
    args = parser.parse_args()
    
    # Query mode
    if args.query:
        if args.query == 'latest':
            log_info(f"Retrieving latest {args.limit} signals...")
            df = get_latest_signals(args.limit)
            if df is not None:
                print(df.to_string())
        elif args.query == 'stats':
            log_info("Computing signal statistics...")
            df = get_signal_statistics()
            if df is not None:
                print(df.to_string())
        elif args.query == 'ticker' and args.ticker:
            log_info(f"Retrieving signals for {args.ticker}...")
            df = get_signals_by_ticker(args.ticker, args.limit)
            if df is not None:
                print(df.to_string())
        elif args.query == 'accuracy':
            if args.ticker:
                log_info(f"Retrieving accuracy for {args.ticker}...")
                perf = get_model_performance_by_ticker(args.ticker)
                if perf is not None:
                    print(f"\nModel Accuracy for {args.ticker}:")
                    print(f"  Accuracy:  {perf['accuracy']:.4f} (±{perf['accuracy_std']:.4f})")
                    print(f"  Precision: {perf['precision']:.4f} (±{perf['precision_std']:.4f})")
                    print(f"  Recall:    {perf['recall']:.4f} (±{perf['recall_std']:.4f})")
                    print(f"  F1-Score:  {perf['f1_score']:.4f} (±{perf['f1_score_std']:.4f})")
                    print(f"  ROC-AUC:   {perf['roc_auc']:.4f} (±{perf['roc_auc_std']:.4f})")
                    print(f"  Total Samples: {perf['total_samples']}")
                    print(f"  Buy Signals:   {perf['bullish_signals']}")
                    print(f"  Sell Signals:  {perf['bearish_signals']}")
                    print()
            else:
                log_info("Displaying model accuracy for all tickers...")
                display_model_performance_summary()
        elif args.query == 'performance':
            log_info("Retrieving model performance metrics...")
            df = get_model_performance()
            if df is not None:
                display_model_performance_summary()
        sys.exit(0)
    
    # Generation mode (default)
    log_pipeline_start("ML Signal Engine", target="all tickers")
    
    try:
        signals_df = generate_ml_signals()
        if signals_df is not None:
            log_pipeline_end("ML Signal Engine", status="SUCCESS")
        else:
            log_pipeline_end("ML Signal Engine", status="FAILED")
            sys.exit(1)
    except KeyboardInterrupt:
        log_warning("Pipeline interrupted by user")
        log_pipeline_end("ML Signal Engine", status="INTERRUPTED")
        sys.exit(1)
    except Exception as e:
        log_exception(e, "ML Signal Engine failed")
        log_pipeline_end("ML Signal Engine", status="FAILED")
        sys.exit(1)